const ActionType = {
    SET_LOGIN: "SET_LOGIN",
    SET_LOGOUT: "SET_LOGOUT",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_ERROR: "LOGIN_ERROR",
    LOGIN_USER: "LOGIN_USER",
    GET_SIGNUP: "GET_SIGNUP",
    SET_SIGNUP: "SET_SIGNUP",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_ERROR: "SIGNUP_ERROR",
    GET_CONSULTANTS: 'GET_CONSULTANTS',
    SET_CONSULTANTS: 'SET_CONSULTANTS'
}

export default ActionType;