const ActionType = {
    SET_LOGIN: "SET_LOGIN",
    SET_LOGOUT: "SET_LOGOUT",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_ERROR: "LOGIN_ERROR",
    LOGIN_USER: "LOGIN_USER",
    GET_SIGNUP: "GET_SIGNUP",
    SET_SIGNUP: "SET_SIGNUP",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_ERROR: "SIGNUP_ERROR",
    SET_STORE_REGISTRATION: 'SET_STORE_REGISTRATION',
    SET_UPDATE_PERSONAL_INFO: 'SET_UPDATE_PERSONAL_INFO'
}

export default ActionType;